Metrics/LineLength:
  Max: 110
  Exclude:
    - 'Gemfile'
    - 'spec/runners/planningalerts_spec.rb'
Metrics/BlockLength:
  Exclude:
    - 'spec/unit_spec.rb'
    - 'spec/runner_spec.rb'
    - 'spec/runners/planningalerts_spec.rb'
